# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.13'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build 
  displayName: 'npm install and build'
- task: CopyFiles@2
  inputs:
    SourceFolder: './dist/movematepro'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'
 
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'www'
 
- bash: echo "Hello world"
- bash: ls $(System.ArtifactsDirectory)
- bash: ls $(Pipeline.Workspace)/s
 
- task: FtpUpload@2
  inputs:
    credentialsOption: 'inputs'
    serverUrl: 'ftp://emiratesbay.com'
    username: 'movemateuser'
    password: 'movemate@123'
    rootDirectory: '/home/vsts/work/1/s/dist/movematepro'
    filePatterns: '**'
    remoteDirectory: '/'
    clean: false
    cleanContents: false
    preservePaths: true
    trustSSL: false
